### ISSUE TITLE
Is there any method to hook input?

### ISSUE THREAD

**Issue by hcaihao** [TinyTinni/PyLogHook#1]
I want to read input string from c++.

Help pls, Thank you!

**Comment by TinyTinni** [comment]
Hi,
no, this one here only supports ostream from python to c++.
pybind11 supports [ostream_redirect](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/utilities.html#capturing-standard-output-from-ostream), which maybe implements, what you are looking for (C++ ostream -> Python ostream).

**Comment by hcaihao** [comment]
Thanks for your reminding, i'll look at it.

**Comment by hcaihao** [comment]
Sorry, I'm newbe to python & pybind, so I can't work out, could you do me a favor?

**Comment by TinyTinni** [comment]
Maybe, if you share more details to your problem.
But, neither this one nor, to my knowledge, pybind11 has a wrapper for c++ istreams.
If you want this, you have to write a mechanic and a, for your problem, suitable expose function on your own. 
I.e. you can expose to python via pybind11 the [std::getline](https://en.cppreference.com/w/cpp/string/basic_string/getline) function using your istream or a custom function, based on std::getline, which returns a string instead of a istream. Something like this:

```cpp
// m is a pybind11 module
// my_stream is a istream
m.def("read_from_my_stream", [&my_stream]() {
   std::string r;
   std::getline(my_stream, r);
   return r;
    );
});
```

Similar if you use boost::python.

**Comment by hcaihao** [comment]
Ok, I'll post here if I solve it, thanks a lot!

**Comment by TinyTinni** [comment]
Ok, you can reopen the issue or append a comment on it.

**Comment by hcaihao** [comment]
Hi, the solution is very simple, just override readline function in sys module.
